---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ngnix-deployment
 type: proxy
spec:
 replicas: 3
 selector:
  matchLabels:
   type: proxy
 template:
  metadata:
   name: nginx-pod
   lablels:
    type: proxy
 spec:
  containers:
   - name: nginx
     image: nginx
...