---
apiVersion: v1
kind: Pod
metadata:
 name: jenkins-pod
 labels:
  author: manohar
  type: ci-cd
spec:
 containers:
  - name: jenkins
    image: jenkins/jenkins
	ports: #this is not good practice
	 - containerPort: 8080
	   hostPort: 9090
...
