---
apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  author: manohar
  type: proxy
spec:
 containers:
  - name: webserver
    image: nginx
	ports: 
	 - containerPort: 80
	   hostPort: 8080
...
