---
apiVersion: v1
kind: Pod
metadata:
 name: postgres-pod
 labels:
  author: manohar
  type: db
spec:
 containers:
  - name: mydb
    image: postgres
	env:
	 - name: POSTGRES_PASSWORD
	   value: manohar
	 - name: POSTGRES_USER
	   value: myuser
	 - name: POSTGRES_DB
       value: mydb
...